version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
          max-file: 2
          max-size: 70m
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '2G'
        reservations:
          cpus: '0.4'
          memory: '1G'