version: '3.9'

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    logging:
      driver: "json-file"
      options:
          max-file: 2
          max-size: 20m
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '512M'
        reservations:
          cpus: '0.2'
          memory: '256M'
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    logging:
      driver: "json-file"
      options:
          max-file: 2
          max-size: 20m
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '512M'
        reservations:
          cpus: '0.2'
          memory: '256M'