version: '3.8'

services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:2.1.10-debug
    user: root
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./output_logs:/fluent-bit/etc/output_logs
    ports:
      - "24224:24224"