receivers:
    otlp:
        protocols:
            http:
                # endpoint: '172.29.17.18:4318'
            grpc:
                # endpoint: '172.29.17.18:4317'

exporters:
    logging:
        loglevel: debug
    # jaeger:
    #     endpoint: jaeger-all-in-one:14250
    #     tls:
    #         insecure: true
    # elasticsearch/trace:
    #     endpoints: [https://es01:8200]
    #     headers:
    #         # Elastic APM Server secret token
    #         Authorization: "Bearer ThisIsMySecretToken123++"
    #     tls:
    #         insecure: true
    otlp/elastic: 
        # Elastic APM server https endpoint without the "https://" prefix
        endpoint: "localhost:8200"
        headers:
            # Elastic APM Server secret token
            Authorization: "Bearer AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2OTMxNDgwMjE4MjY6QUE4Z3RsVVhSUFNRelp5VHdQcm91dw"
        # tls:
        #     insecure: true

processors:
    memory_limiter:
        check_interval: 1s
        limit_mib: 2000
    batch:

extensions:
    health_check:
    pprof:
    zpages:
        endpoint: 0.0.0.0:55679

service:
    extensions: [health_check, pprof, zpages]
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp/elastic]
            processors: [memory_limiter, batch]
        metrics:
            receivers: [otlp]
            exporters: [otlp/elastic]
            processors: [batch]
        logs:
            receivers: [otlp]
            exporters: [otlp/elastic]