receivers:
    otlp:
        protocols:
            http:
                # endpoint: '172.29.17.18:4318'
            grpc:
                # endpoint: '172.29.17.18:4317'

exporters:
    logging:
        loglevel: debug
    # jaeger:
    #     endpoint: jaeger-all-in-one:14250
    #     tls:
    #         insecure: true
    # elasticsearch/trace:
    #     endpoints: [https://elasticsearch:9200]
    #     traces_index: traces-apm-jenkins
    #     pipeline: traces-apm-8.9.1
    #     tls:
    #         insecure: false
    #     cert_file: certs/elasticsearch/elasticsearch.crt
    #     key_file: certs/elasticsearch/elasticsearch.key
    #     user: elastic
    #     password: Password123++
    #     # api_key: AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2OTMxNDgwMjE4MjY6QUE4Z3RsVVhSUFNRelp5VHdQcm91dw
    #     retry:
    #         max_requests: 5
    # elasticsearch/log:
    #     endpoints: [https://elasticsearch:9200]
    #     logs_index: logs-apm.app.jenkins-base
    #     pipeline: logs-apm.app-8.9.1
    #     tls:
    #         insecure: false
    #     cert_file: certs/elasticsearch/elasticsearch.crt
    #     key_file: certs/elasticsearch/elasticsearch.key
    #     user: elastic
    #     password: Password123++
    #     # api_key: AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2OTMxNDgwMjE4MjY6QUE4Z3RsVVhSUFNRelp5VHdQcm91dw
    #     retry:
    #         max_requests: 5
    #     sending_queue:
    #         enabled: true
    #         num_consumers: 20
    #         queue_size: 1000
    otlp/elastic:
        # Elastic APM server https endpoint without the "https://" prefix
        endpoint: "localhost:8200"
        headers:
            # Elastic APM Server secret token
            Authorization: "Bearer AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2OTMxNDgwMjE4MjY6QUE4Z3RsVVhSUFNRelp5VHdQcm91dw"
        # tls:
        #     insecure: true

processors:
    resource:
        attributes:
        - key: service.name
          value: "jenkins"
          action: insert
        - key: service.version
          value: "1.0.0"
          action: insert
        - key: deployment.environment
          value: "production"
          action: insert
    memory_limiter:
        check_interval: 1s
        limit_mib: 2000
    batch:

extensions:
    health_check:
    pprof:
    zpages:
        endpoint: 0.0.0.0:55679

service:
    extensions: [health_check, pprof, zpages]
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp/elastic]
            processors: [memory_limiter, batch]
        # metrics:
        #     receivers: [otlp]
        #     exporters: [otlp/elastic]
        #     processors: [batch]
        logs:
            receivers: [otlp]
            exporters: [otlp/elastic]
